# Generated by Django 2.0.7 on 2018-08-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedvideos',
            name='path',
            field=models.FilePathField(path='mysite/media/'),
        ),
    ]
