# Generated by Django 2.0.7 on 2018-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180814_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedvideos',
            name='path',
            field=models.FilePathField(path='/mysite/media/'),
        ),
    ]
