# Generated by Django 2.0.7 on 2018-08-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180814_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedvideos',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
