# Generated by Django 2.0.7 on 2018-08-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_downloadedvideos_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedvideos',
            name='path',
            field=models.FilePathField(path='/mysite/media'),
        ),
    ]
