# Generated by Django 2.0.7 on 2018-08-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180814_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadedvideos',
            name='path',
            field=models.FilePathField(path='/home/nimish/Desktop/Projects/Django/mysite/mysite/media'),
        ),
    ]
