# Generated by Django 2.0.7 on 2018-08-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180814_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedvideos',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
